version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  frontend:
    image: zayan93/frontend_v1:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: zayan93/backend_v1:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always

    depends_on:
            - backend
            - frontend

volumes:
    static_value:
    media_value:
